default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_rails_react_development
  username: dilsh
  password: dilsher
  host: localhost
  port: 5432

test:
  <<: *default
  database: hello_rails_react_test
  username: dilsh
  password: dilsher
  host: localhost
  port: 5432

production:
  <<: *default
  database: hello_rails_react_production
  username: hello_rails_react
  password: <%= ENV["HELLO_RAILS_REACT_DATABASE_PASSWORD"] %>
